# Amazon Sales - Exploratory Data Analysis

This project explores the sales data of products on Amazon, with a focus on understanding the relationship between discounts, ratings, and reviews. The dataset includes information on categories, discounted and actual prices, discount percentages, ratings, rating counts, review titles, and review content. 

The <b>goal</b> of this exploratory data analysis is to gain insights into the factors that impact sales on Amazon and to identify any interesting trends or patterns in the data. By analyzing this dataset, I hope to gain insights that can inform future marketing and sales strategies for businesses selling on Amazon.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/IpshitaSingh/Datasets/main/amazon_sales.csv')

In [3]:
df.head()

product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...   
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   
2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...   
3  B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...   
4  B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...   

                                            category discounted_price  \
0  Computers&Accessories|Accessories&Peripherals|...             ₹399   
1  Computers&Accessories|Accessories&Peripherals|...             ₹199   
2  Computers&Accessories|Accessories&Peripherals|...             ₹199   
3  Computers&Accessories|Accessories&Peripherals|...             ₹329   
4  Computers&Accessories|Accessories&Peripherals|...             ₹154   

  actual_price discount_percentage rating rating_count  \
0       ₹1,099                 64%    4.2       24,269   
1         ₹349                 43%    4.0       43,994   
2       ₹1,899                 90%    3.9        7,928   
3         ₹699                 53%    4.2       94,363   
4         ₹399                 61%    4.2       16,905   

                                       about_product  \
0  High Compatibility : Compatible With iPhone 12...   
1  Compatible with all Type C enabled devices, be...   
2  【 Fast Charger& Data Sync】-With built-in safet...   
3  The boAt Deuce USB 300 2 in 1 cable is compati...   
4  [CHARGE & SYNC FUNCTION]- This cable comes wit...   

                                             user_id  \
0  AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...   
1  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...   
2  AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...   
3  AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...   
4  AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...   

                                           user_name  \
0  Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...   
1  ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...   
2  Kunal,Himanshu,viswanath,sai niharka,saqib mal...   
3  Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...   
4  rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...   

                                           review_id  \
0  R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...   
1  RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...   
2  R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...   
3  R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...   
4  R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...   

                                        review_title  \
0  Satisfied,Charging is really fast,Value for mo...   
1  A Good Braided Cable for Your Type C Device,Go...   
2  Good speed for earlier versions,Good Product,W...   
3  Good product,Good one,Nice,Really nice product...   
4  As good as original,Decent,Good one for second...   

                                      review_content  \
0  Looks durable Charging is fine tooNo complains...   
1  I ordered this cable to connect my phone to An...   
2  Not quite durable and sturdy,https://m.media-a...   
3  Good product,long wire,Charges good,Nice,I bou...   
4  Bought this instead of original apple, does th...   

                                            img_link  \
0  https://m.media-amazon.com/images/W/WEBP_40237...   
1  https://m.media-amazon.com/images/W/WEBP_40237...   
2  https://m.media-amazon.com/images/W/WEBP_40237...   
3  https://m.media-amazon.com/images/I/41V5FtEWPk...   
4  https://m.media-amazon.com/images/W/WEBP_40237...   

                                        product_link  
0  https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...  
1  https://www.amazon.in/Ambrane-Unbreakable-Char...  
2  https://www.amazon.in/Sounce-iPhone-Charging-C...  
3  https://www.amazon.in/Deuce-300-Resistant-Tang...  
4  https://www.amazon.in/Portronics-Konnect-POR-1...

In [4]:
df.shape

(1465, 16)

In [5]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [6]:
df = df.dropna()

In [7]:
new_df = df.drop(['product_id', 'product_name', 'about_product', 'user_id', 'user_name', 'review_id', 'img_link', 'product_link'], axis = 1)

In [8]:
new_df.columns

Index(['category', 'discounted_price', 'actual_price', 'discount_percentage',
       'rating', 'rating_count', 'review_title', 'review_content'],
      dtype='object')

In [9]:
new_df['discounted_price'] = new_df['discounted_price'].str.replace(',', '').str.replace('₹', '')
new_df['actual_price'] = new_df['actual_price'].str.replace(',', '').str.replace('₹', '')
new_df['discount_percentage'] = new_df['discount_percentage'].str.replace('%', '')
new_df['rating'] = new_df['rating'].str.replace('|', '')
new_df['rating_count'] = new_df['rating_count'].str.replace(',', '')

In [10]:
cols = ['discounted_price', 'actual_price', 'discount_percentage', 'rating', 'rating_count']
new_df[cols] = new_df[cols].apply(pd.to_numeric, errors='ignore')

In [11]:
new_df.dtypes

category                object
discounted_price       float64
actual_price           float64
discount_percentage      int64
rating                 float64
rating_count             int64
review_title            object
review_content          object
dtype: object

In [12]:
new_df.describe()

discounted_price   actual_price  discount_percentage       rating  \
count       1463.000000    1463.000000          1463.000000  1462.000000   
mean        3129.277122    5451.068544            47.650718     4.096717   
std         6948.222850   10881.018448            21.622373     0.289497   
min           39.000000      39.000000             0.000000     2.000000   
25%          325.000000     800.000000            32.000000     4.000000   
50%          799.000000    1690.000000            50.000000     4.100000   
75%         1999.000000    4312.500000            63.000000     4.300000   
max        77990.000000  139900.000000            94.000000     5.000000   

        rating_count  
count    1463.000000  
mean    18295.541353  
std     42753.864952  
min         2.000000  
25%      1186.000000  
50%      5179.000000  
75%     17336.500000  
max    426973.000000

<h4>Insights</h4>

* The average discounted price is ₹3129.28, while the average actual price is ₹5451.07. This suggests that, on average, items are being sold at a discount on Amazon


* The average discount percentage is 47.65%, which is a significant discount


* The average rating is 4.10, with a standard deviation of 0.29, indicating that most items have high ratings


* The minimum discounted price and actual price are the same at ₹39, while the maximum discounted price is ₹77990 and the maximum actual price is ₹139900, suggesting that there is a wide range of prices for items on Amazon


* The median rating is 4.1, which is the same as the mean, indicating a roughly symmetric distribution of ratings


* The median rating count is 5179, which is much lower than the mean, meaning that a few products have a really high number of ratings, but most of the products have a much lower number of ratings.

<h3>Visualization</h3>

My objective is to utilize this dataset for the purpose of obtaining answers to the following questions:

> What are the top-selling product categories on Amazon? 

> What is the average discount percentage on these categories?

> Do products in these categories offer the highest discounts?

> Does the category of a product have an impact on its rating?

Relationship between review title/content and rating: It would be interesting to see if there are any specific keywords or phrases that are commonly used in high-rated reviews.

<h5>What are the top-selling categories on Amazon?</h5>

In [13]:
# Grouping the data by the "category" column and getting the sum of rating count for each category to find popular categories
sales_by_category = new_df.groupby('category')['rating_count'].sum()

# Sorting the series in descending order to get the top 10 categories
top_categories = sales_by_category.sort_values(ascending=False).head(10)

top_categories

category
Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear                         4204939
Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables    3547816
Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones                 2493269
Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables                       1906054
Electronics|WearableTechnology|SmartWatches                                          1644476
Electronics|Accessories|MemoryCards|MicroSD                                          1113592
Computers&Accessories|ExternalDevices&DataStorage|PenDrives                           774744
Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions                         760279
Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters           727113
Electronics|Mobiles&Accessories|MobileAccessories|Chargers|PowerBanks                 688810
Name: rating_count, dtype: int64

In [19]:
# Create bar chart
plt.barh(top_categories.index, top_categories.values, color='mediumaquamarine')

plt.style.use('ggplot')

# Set title and labels
plt.title('Top Selling Categories on Amazon', fontsize=18)
plt.xlabel('Total Rating Count (in 100,000)', fontsize=14)
plt.ylabel('Category', fontsize=14)
    
# Display the chart
plt.show()


<h5>How much discount is offered on average for each top category?</h5>

In [15]:
avg_discount_by_category = new_df.groupby('category')['discount_percentage'].mean()

In [16]:
rating_and_discount = pd.concat([sales_by_category, avg_discount_by_category], axis=1)
rating_and_discount.sort_values('rating_count', ascending=False, inplace=True)
top_categories_discounts = rating_and_discount.head(10)

In [17]:
# Plot the top 10 selling categories with their average discount
top_categories_discounts.plot(kind='barh', y='discount_percentage', color='teal', width = 0.8)
 
plt.style.use('ggplot')
    
plt.title('Average Discount by Top Selling Categories', fontsize=18)
plt.xlabel('Average Discount (%)', fontsize = 14)
plt.ylabel('Category', fontsize = 14)

plt.show()

<h4>Insights</h4>

* This graph suggests that level of discount doesn't necessarily correlate with the number of sales. The fact that the 1st ranking category doesn't have the highest discount suggests that customers may be more interested in other factors such as the product quality, brand reputation, or unique features.


* The 3rd category's (smart phones and mobile phones) low discount level could indicate that the products in this category are highly desirable and therefore don't require as much discounting to sell well. On the other hand, the 5th category's (smartwatches) high level of discount may suggest that the products are not selling as well and require a discount to entice customers.


* The varying levels of discount among the top 10 categories suggest that the website is using a targeted pricing strategy based on the demand and competition within each category.

<h5>Does the category of a product have an impact on its rating?</h5>

In [58]:
# Create a scatter plot
plt.scatter(new_df['category'], new_df['rating'], c=new_df['rating'], cmap='RdPu',alpha=0.5)

# Set the plot title and axis labels
plt.title("Relationship between Category and Rating")
plt.xlabel("Categories")
plt.ylabel("Rating")

plt.xticks([])

# Show the plot
plt.show()

<h4>Insights</h4>

* Products in this dataset seem to be good quality as most ratings are between 4.0 and 4.5


* More products fall in the range of 3.5 to 4 than in the range of 4.5 to 5, suggesting that a larger proportion of products are rated slightly lower than the highest-rated products.


* A limited number of products have either a significantly high or low rating.

<h2>Conclusion</h2>

On average, Amazon products are sold at a discount with an average discount percentage of 47.65%.

Most Amazon products have high ratings with an average rating of 4.10 and a standard deviation of 0.29.

The price range for Amazon products is wide, with the minimum price being ₹39 and the maximum discounted price being ₹77,990.

The top-selling categories on Amazon have varying levels of discounts, which may be based on competition and demand within each category.

Products in the smartphone category have a lower discount percentage compared to other categories, suggesting high demand.

Products with a high discount percentage may not be selling as well and require discounts to attract customers.

There is a limited number of products with either very high or very low ratings, most products have moderate rating.

Most products in this dataset seem to be of good quality.